/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Practice extends SchemaImpl {

    private static final long serialVersionUID = 2123843400;

    /**
     * The reference instance of <code>practice</code>
     */
    public static final Practice PRACTICE = new Practice();

    /**
     * The table <code>practice.user</code>.
     */
    public final User USER = com.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Practice() {
        super("practice", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
