/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in practice
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>practice.user</code>.
     */
    public static final User USER = com.generator.tables.User.USER;
}
